# Generated by Django 2.2 on 2022-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=20)),
                ('files', models.IntegerField(default=0)),
                ('links', models.IntegerField(default=0)),
            ],
        ),
    ]
